### PR TITLE
Add SN TECH T3 Gaming Mouse

### PR DESCRIPTION
**Pull request by Doomsdayrs**
The SN TECH T3 is a very obscure mouse from about a half decade or so ago.

I had it laying around, and added it.

There are some issues with its configuration, but that is another story.

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
> Just to confirm, the buttons don't work on this device?

Buttons are recognized as MB8 and 9 with xev, but are not configurable by piper. I have the old windows software backed up if you want it.

Preview images:
Screenshot from 2022-01-14 00-48-59
Screenshot from 2022-01-14 00-49-06

LED is also represented. Off = Cycle, Cycle = Off.

**Comment by Doomsdayrs** [comment]
The actual mouse has a T logo, but i am not sure if that is brand specific or not.

**Comment by Doomsdayrs** [comment]
Checked, It seems the device shares a USB ID

nubwo x7 spectrum
https://github.com/libratbag/libratbag/blob/3f99446a1be984b78eac60e47bfd66e1c674e30c/data/devices/nubwo-x7-spectrum.device

**Comment by Doomsdayrs** [comment]
Further research

It seems the button layout is similar. Likely the same board underneath?

https://www.nubwo.co.th/wp-content/uploads/2018/11/x7.jpg

**Comment by whot** [comment]
hmm, so, I reckon if your mouse is a decade old, can't really be configured anyway and it shares the USB id with one we have in libratbag - how about just making this PR the SVG for the x7 spectrum and squinting really hard whenever you're using your device :)

though judging by my google results, the x7 spectrum is quite obscure as well, I can barely find english (or even latin-script) results other than libratbag.

**Comment by Doomsdayrs** [comment]
> how about just making this PR the SVG for the x7 spectrum and squinting really hard whenever you're using your device :)

But I already have this one done >:(

**Comment by whot** [comment]
sorry, I wasn't clear. All that's needed here is renaming it to "Nubwo x7 Spectrum" in the `.ini` file and the svg name accordingly. No changes needed to the SVG.

**Comment by Doomsdayrs** [comment]
> sorry, I wasn't clear. All that's needed here is renaming it to "Nubwo x7 Spectrum" in the `.ini` file and the svg name accordingly. No changes needed to the SVG.

Does that really make a difference with how obscure these mice are?

**Comment by whot** [comment]
not really. I guess we can wait for the first Nubwo user to complain and then I can drop you both into a dojo to fight to the death :)

**Pull request merged**
