### PR TITLE
Fix typo in profile.capabilities description

### PR DESCRIPTION
**Pull request by stephanlachnit**
Wrong syntax.

### CODE REVIEW

**Comment by stephanlachnit** [comment]
Do not merge. We should edit `ratbagd.py` in libratbag and import it from there. Actually why are we not importing it as a subproject like they did here: https://github.com/FeralInteractive/gamemode/tree/master/subprojects

**Comment by FFY00** [comment]
I don't think this is a typo but it's not my code, so I will leave it to @whot.

**Comment by stephanlachnit** [comment]
> I don't think this is a typo but it's not my code, so I will leave it to @whot.

Pretty sure it is: `is in` is not a valid python call, and it doesn't make sense to differentiate between `RatbagdProfile` (class) and `profile` (variable).

**Comment by FFY00** [comment]
The `is` part might be but the other I am pretty isn't. `CAP_WRITABLE_NAME` is a class variable, not an instance variable. It is present in `profile` because it is instantiated from `RatbagdProfile` but `CAP_WRITABLE_NAME` is not an instance variable, it is not specific for `profile`.

**Comment by stephanlachnit** [comment]
> variable



> The `is` part might be but the other I am pretty isn't. `CAP_WRITABLE_NAME` is a class variable, not an instance variable. It is present in `profile` because it is instantiated from `RatbagdProfile` but `CAP_WRITABLE_NAME` is not an instance variable, it is not specific for `profile`.

That's true, but I thought that this is more an actual code example, and here `RatbagdProfile.CAP_WRITABLE_NAME` will not work afaik.

**Comment by FFY00** [comment]
Why wouldn't it work?

**Comment by stephanlachnit** [comment]
> Why wouldn't it work?

Code returns with `NameError: name 'RatbagProfile' is not defined`. Python works here different than C.

**Comment by FFY00** [comment]
It needs to be imported.

**Comment by stephanlachnit** [comment]
> It needs to be imported.

But that's useless bloat, since you have the variable anyway.

**Comment by FFY00** [comment]
I would not say that. It helps redability, it states where that variable came from.

**Comment by stephanlachnit** [comment]
> I would not say that. It helps redability, it states where that variable came from.

I thought about it and that's actually a very good point. Closing this anyway since it will be included the PRs for the disabled resolutions functionaliy.

**Comment by whot** [comment]
> Do not merge. We should edit ratbagd.py in libratbag and import it from there. 

fwiw, changes to `ratbagd.py` can flow either way.

> Actually why are we not importing it as a subproject [...]

there's still the grand idea on the horizon that once libratbag's API is stable, we don't need to copy `ratbagd.py` back and forth anymore and it can be tailored more precisely to each project.

The `is in` was a typo, yes. The class name was intentional to make it more obvious where it comes from. Since it's documentation, I'm playing a bit loose here with actual code accuracy ;)

**Pull request closed without merging**
