### PR TITLE
Add SVG for Roccat Kone Pure

### PR DESCRIPTION
**Pull request by stephanlachnit**
Basically took @hipnoizz's design from #326, replaced the LED logo with the one from the G403 and removed the up & down buttons for the scroll wheel.

Signed-off-by: Stephan Lachnit <stephanlachnit@protonmail.com>

### CODE REVIEW

**Comment by stephanlachnit** [comment]
There appears to be a problem, but since I'm new to Inkscape and can't really test since I don't have this mouse I might need some help. This is the error warning from CircleCI, but sadly it's not exactly helpful:
`ERROR:svgs/roccat-kone-pure.svg:Width is outside of range: 500.0`
`ERROR:svgs/roccat-kone-pure.svg:Height is outside of range: 500.0`

**Comment by stephanlachnit** [comment]
I just realized that there is no support for the Roccat Kone Pure in libratbag yet, see https://github.com/libratbag/libratbag/pull/682. So this probably shouldn't get merged until someone tackles this problem again (if the svg is okay #326 can still be closed I guess).

**Comment by FFY00** [comment]
Okay. Btw, you can trick piper into using your SVG by replacing the SVG of a mouse that you do have with this one.

**Comment by stephanlachnit** [comment]
Thanks for the hint! I just rebased it see if it passes CircleCI with #440 merged. I think I can adjust the changes from libratbag/libratbag#682 to be ready to merge, but I definitely can't test if it actually works.

**Comment by stephanlachnit** [comment]
Since there's now support in libratbag this could be merged. However is it maybe possible to release a new version of piper before that? Because there have been several devices added in libratbag 0.11, which are now supported in piper, but piper didn't had a special release for this version.

**Comment by whot** [comment]
yes, planning to do a piper/libratbag release this week just so we flush the pipes before the long holiday period

**Comment by FFY00** [comment]
@whot please ping me before if you can. I want to try a get https://github.com/libratbag/libratbag/pull/829 merged before the release.

**Pull request merged**
