### PR TITLE
Don't close/accept macro dialog on esc/enter to allow binding these keys

### PR DESCRIPTION
**Pull request by AlexP11223**
#322

### CODE REVIEW

**Comment by Cxarli** [comment]
Could I please bump this? My current workaround is very dirty and this would be a lifesaver.

**Comment by FFY00** [comment]
@stephanlachnit do you have some time to look at this?

**Comment by stephanlachnit** [comment]
I can take a look at it today.

**Comment by stephanlachnit** [comment]
Yep works, code is fine as well

**Pull request merged**
