### PR TITLE
Add 250 Hz polling rate

### LINKED ISSUE #491: Set polling rate below 500?
Some games in wine have issues with high polling rates and even 500 will cause some lag, however, this software can only go down to 500 even though in windows it can reach 250

I'd like the ability to change polling rates to 250 and 750 in settings

Currently configuring polling rates in terminal is a chore

### PR DESCRIPTION
**Pull request by stephanlachnit**
Fixes #491. Still need to test it.

### CODE REVIEW

**Comment by stephanlachnit** [comment]
I'm not entirely sure why but it doesn't work.

**Comment by stephanlachnit** [comment]
Ok nvm stupid mistake by me, but I get some weird behavior with my G Pro: if I set 250 Hz, ratbagctl reports 200 Hz. @FFY00 any idea why that is the case? @cncz42 can you test it and report as well?

**Comment by FFY00** [comment]
That seems weird.

Can you paste the feature list (easiest way is `solaar show`)?

**Comment by stephanlachnit** [comment]
> That seems weird.

It really doesn't make any sense to me either. Can you reproduce it with any of your devices?

What I just found out, what makes it even weirder: it now default to 250 Hz when reconnecting (I set it once to 250 Hz in Windows), even though I set back to 1000 Hz in Piper.

> Can you paste the feature list (easiest way is `solaar show`)?

`solaar: error: Logitech receiver not found`, I have a G Pro but not the wireless one.

**Comment by stephanlachnit** [comment]
Setting it with this commit to 125 Hz results in `ratbagctl` showing 100 Hz.

**Comment by staticssleever668** [comment]
This is a problem on ratbagd side. https://github.com/libratbag/libratbag/pull/1161 fixes it.

**Comment by whot** [comment]
Fixed with #703, sorry about this lingering so long

**Pull request closed without merging**
