### PR TITLE
adding support for Logitech MX Anywhere 3 - mouse with single configuration for Bluetooth/USB

### PR DESCRIPTION
**Pull request by erdincay**

### CODE REVIEW

**Comment by erdincay** [comment]
image

**Comment by erdincay** [comment]
I don't get the check for Ubuntu 20.04, I use Pop! 20.04, build it, tested it, and works fine. The file that is stated as missing is in the given folder, will now recheck if my commit failed to transfer it.

**Comment by erdincay** [comment]
everything looks quite fine, I do not understand the issue with the checkers, the SVG file has to be modified to fit the MX Anywhere 3 better, but that is a task someone from your side has to do

PS: also I will add additional device IDs when testing my mouse on different connections on different machines

**Comment by erdincay** [comment]
differences between Anywhere 2 vs Anywhere 3: **left-wheel movement, and right-wheel movement do not exist anymore**

**Comment by whot** [comment]
>  do not understand the issue with the checkers, 

It's a sorting issue but it should be fixed with #711 which gets rid of this altogether, can you please rebase onto that? Thanks.

**Comment by whot** [comment]
Thanks! I've rebased this locally and put your patch on top, removes the merge request, please see #716

**Comment by erdincay** [comment]
> Thanks! I've rebased this locally and put your patch on top, removes the merge request, please see #716

Hi, thanks, I also rebased and pushed the changes. I was sick yesterday, sry for inconvenience. Have a nice weekend!

**Pull request closed without merging**
