### PR TITLE
ResolutionRow: add label to highlight the active resolution

### PR DESCRIPTION
**Pull request by Hjdskes**
The same approach should work for showing and setting the default resolution (see #36) so I'll look into fixing that too. Note that this depends on an incoming patch to ratbagd.

### CODE REVIEW

**Comment by Hjdskes** [comment]
See https://github.com/libratbag/libratbag/pull/284.

**Comment by Hjdskes** [comment]
Whoops, I forgot to mention that this also fixes #81 and therefore overrides #72, although I still don't get how that can work given that the changes do have to be committed first.

**Comment by whot** [comment]
feel free to push the first three commits, they're semi-unrelated and can go in

**Comment by Hjdskes** [comment]
> feel free to push the first three commits, they're semi-unrelated and can go in

Thanks, done. Looking into the bug now.

**Comment by Hjdskes** [comment]
I cannot reproduce your bug @whot. I have two resolutions in a single profile both with a DPI of 2700, one of which is active. If I start Piper, only the active one is labelled active -- the other isn't. Are you sure this isn't something on your end, where ratbagd/libratbag/your device has two resolutions active?

**Comment by whot** [comment]
merged, will file an issue if it's still broken here but meanwhile let's get this in

**Pull request merged**
