### PR TITLE
data: add SVG for the Mx Master 3

### PR DESCRIPTION
**Pull request by emericg**

### CODE REVIEW

**Comment by FFY00** [comment]
Can you post a preview here?

**Comment by emericg** [comment]
Here you go. I've drawn it myself from a photo of the mouse facing up. Ratbag support for this mouse is completly broken, but at least it's pretty now ^^

logitech-mx-master-3 svg

**Comment by FFY00** [comment]
Thanks, looks great!

Unfortunately, the hardware is the limitation. It does not let us do nearly as much as the gaming line, most of the stuff in the Windows driver is done in software.

**Comment by FFY00** [comment]
The `check-svg` check is complaining about two things.

```
ERROR:svgs/logitech-mx-master-3.svg:Missing led0-leader for led0
ERROR:svgs/logitech-mx-master-3.svg:Missing led0-path for led0
```

**Comment by emericg** [comment]
I shouldn't have tag this led0 then, it's not an user configurable LED (as far as I know).

**Comment by FFY00** [comment]
Thanks!

**Pull request merged**
