### PR TITLE
add 125 and 250 rates

### PR DESCRIPTION
**Pull request by kyokenn**
Fixes https://github.com/libratbag/piper/issues/674

### CODE REVIEW

**Comment by paul-canada** [comment]
How I can apply this fix ? 
Thanks.

**Comment by kyokenn** [comment]
> How I can apply this fix ? Thanks.

You can wait until it get reviewed by maintainers and merged, or you can patch it by yourself or download my repository.

**Comment by paul-canada** [comment]
Yes, I can wait the upgrade.
1. How I can patch ? 
2. I downloaded also your file piper-master.zip (23 Dec). How upgrade piper 0.6 ? 
Thanks for your help.

**Comment by kyokenn** [comment]
> I downloaded also your file piper-master.zip (23 Dec). How upgrade piper 0.6 ?

Now you have to unpack, build and install it or you can try to replace those 2 files that I have changed where you have already installed piper.

**Comment by paul-canada** [comment]
> Now you have to unpack, build and install it or you can try to replace those 2 files that I have changed where you have already installed piper.
I failed to compile because my ratbagd is too old and for patch I did not find the file ResolutionsPage.ui 

I think I will wait the "official" update. 
Thanks for your Fixes. :)

**Comment by paul-canada** [comment]
> Now you have to unpack, build and install it or you can try to replace those 2 files that I have changed where you have already installed piper.
    
I failed to compile because my ratbagd is too old and for patch I did not find the file ResolutionsPage.ui

I think I will wait the "official" update.
Thanks for your Fixes. :)

**Comment by Ablinne** [comment]
I have just tried this patch and there seems to be a missing UI update when switching to a profile (via profile chooser in the top left) that uses one of the new refresh rates. The UI stays on the refresh value from the previously selected profile.

**Comment by kyokenn** [comment]
>I have just tried this patch and there seems to be a missing UI update when switching to a profile

I can't reproduce that. Make sure that you are testing with "piper.devel" instead of "piper", otherwise you will get imported the default system-wide installed piper modules.

Also did you compared the real rate values as reported by ratbagctl <device> info ?

**Comment by Ablinne** [comment]
I installed it system wide by modifying the PKGBUILD from the AUR package piper-git (changed only source to this branch, left everything else as it was). When restarting piper, the correct rate was shown again. I didn't try ratbagctl though. I'm out of time for today, I hope that I manage to revisit this tomorrow of the day after.

**Comment by whot** [comment]
Merged, thanks! I'd appreciate a follow-up to check if those resolutions are actually available on the device (they are exported as the `ReportRates` property) and only showing them conditionally.

**Comment by kyokenn** [comment]
>I'd appreciate a follow-up to check if those resolutions are actually available on the device (they are exported as the ReportRates property) and only showing them conditionally.

Nice. I didn't know about it. I thought it was a planned feature (exposing list of supported options) - https://github.com/libratbag/libratbag/issues/1170

**Comment by whot** [comment]
that issue relates to device capabilities which is a slightly different circle in the venn diagram :) the report rates are already available as the [`report_rates` property](https://github.com/libratbag/piper/blob/master/piper/ratbagd.py#L490)

**Comment by Ablinne** [comment]
@whot I double checked, G-Hub offers 125 and 250 as rate settings. Even more strange: As long as I don't *set* it using ratbagctl, it is reported correctly as 125
```
alex@galaxy:~$ ratbagctl "Logitech MX518 Gaming Mouse" rate get
125
````
When I set  it once, from then on I only get 100/200.

**Pull request merged**
