### PR TITLE
Re-Add Logitech G Pro X Superlight

### LINKED ISSUE #623: Support for Logitech G Pro X Superlight
**Is your feature request related to a problem? Please describe.**
libratbag already supports the device device on master (https://github.com/libratbag/libratbag/commit/104543fdf19f6108b46d311d4a14f32731868261), but piper shows the 404 image.

**Describe the solution you'd like**
It would be nice to have a proper image for that mouse very similar to the image of the G Pro.

### PR DESCRIPTION
**Pull request by brianegan**
Fixes #623, using the device id's from https://github.com/libratbag/libratbag/pull/1122

Screenshot from 2021-01-14 18-31-13

Screenshot from 2021-01-14 18-31-21

### CODE REVIEW

**Comment by brianegan** [comment]
Not quite sure what is up with the Arch server -- having issues with Pacman before running tests I believe.

**Comment by Turbine1991** [comment]
I compiled from your branch, but it doesn't seem to detect my mouse - in either wired or wireless mode.

I'm on Fedora 34:
```
sudo dnf install -y meson libratbag-ratbagd pygobject3-devel python3-flake8

rm -Rf piper
git clone -b "g-pro-x-superlight" https://github.com/brianegan/piper.git
cd piper
meson builddir --prefix=/usr/
ninja -C builddir
sudo ninja -C builddir install
```

**Comment by brianegan** [comment]
Sorry, unfortunately I don't know much about Fedora, but my guess is that the version of libratbag you're using does not support these device IDs.

I've compiled both libratbag and piper from source to get this to work. Furthermore, libratbag only suppots configuring the mouse when it is plugged in. The wireless receiver support has not landed yet.

**Comment by FFY00** [comment]
Yes, exactly.

Sorry for the delay. The arch fail is unrelated.

**Review by FFY00 — APPROVED** [review]

**Pull request merged**
