### PR TITLE
app icon: update style, add source file, add symbolic

### PR DESCRIPTION
**Pull request by bertob**
As discussed in #590

image

This just adds the new assets, and doesn't hook up the symbolic to the build system or switch the code to using the actual app icon instead of the 404 one.

### CODE REVIEW

**Comment by stephanlachnit** [comment]
Thanks again. Any reason the 404 got deleted?

Anyway, the build files need to be updated, but if you want I can also do it.

**Comment by bertob** [comment]
> Any reason the 404 got deleted?

I deleted it because it's the old icon, so it'll have to be replaced with the new one somehow. I was also thinking it might be better to avoid duplicate assets by just using `org.freedesktop.Piper.svg` here.

**Comment by stephanlachnit** [comment]
Sorry for the long waiting period. I wired up Meson support in #602. Currently we can't remove `404.svg`, would require some bigger changes I don't have time for.

Thanks again for the new icon! If there are no last objections, I would merge #602.

**Comment by bertob** [comment]
Sounds great!

**Pull request closed without merging**
