### PR TITLE
Update to new libratbag API

### PR DESCRIPTION
**Pull request by Hjdskes**

### CODE REVIEW

**Comment by phomes** [comment]
Thanks. I tested and Piper works for me again. It does not restrict the slider to the new DPI list, but only uses the min/max values. Better than crashing though :)

**Comment by Hjdskes** [comment]
I don't have that much time atm so preventing the crash is all I can do for now. In three or four weeks I should be able to invest more time in Piper again!

Meanwhile, restricting values shouldn't be that hard... ;)

**Comment by phomes** [comment]
> Meanwhile, restricting values shouldn't be that hard... ;)

So you will do it? Or was that a hint for me to do so?

**Comment by whot** [comment]
thx!

**Pull request merged**
