### PR TITLE
data: add Logitech G100s

### PR DESCRIPTION
**Pull request by FFY00**
I noticed the Logitech G Pro's SVG could be repurposed for this. What do you think?

### CODE REVIEW

**Comment by whot** [comment]
Google suggests the G100s doesn't have the thumb buttons and has no LEDs. So we could re-use the base image and remove those which should only take a few min. But re-using it directly is not ideal, sorry.

Also, the G100s got reverted because it uses a different protocol, should probably wait until libratbag supports again.

**Comment by FFY00** [comment]
Yes, I agree we should wait. Are you talking about the lines? Can't those be hidden in software?

**Comment by whot** [comment]
the lines and the buttons themselves as well. and yes, they could be hidden in software but it takes about 5 min to remove those in inkscape and never think about it again. it takes more than 5 min to write the software to hide those lines on demand, etc. :)

**Comment by FFY00** [comment]
Oh, forgot about the buttons. Makes sense. I am closing this as I don't expect the G100s to be supported that soon.

**Pull request closed without merging**
